# Generated manually for the Book Trailer Lead Finder MVP.
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("keyword", models.CharField(blank=True, max_length=255)),
                ("source_provider", models.CharField(choices=[("csv", "CSV"), ("ddgs", "DDGS"), ("tavily", "Tavily"), ("brave", "Brave"), ("amazon_creators", "Amazon Creators"), ("manual", "Manual")], default="ddgs", max_length=32)),
                ("marketplace", models.CharField(default="US", max_length=16)),
                ("max_books", models.IntegerField(default=25)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("canceled", "Canceled")], default="pending", max_length=16)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("settings_json", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=255)),
                ("normalized_author_key", models.CharField(db_index=True, max_length=255)),
                ("canonical_website", models.URLField(blank=True, max_length=1000)),
                ("contact_page_url", models.URLField(blank=True, max_length=1000)),
                ("publisher_url", models.URLField(blank=True, max_length=1000)),
                ("instagram_url", models.URLField(blank=True, max_length=1000)),
                ("facebook_url", models.URLField(blank=True, max_length=1000)),
                ("tiktok_url", models.URLField(blank=True, max_length=1000)),
                ("youtube_url", models.URLField(blank=True, max_length=1000)),
                ("linkedin_url", models.URLField(blank=True, max_length=1000)),
                ("goodreads_url", models.URLField(blank=True, max_length=1000)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("identity_confidence", models.FloatField(default=0)),
                ("identity_reason", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoNotContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("illustrator_name", models.CharField(blank=True, max_length=255)),
                ("asin", models.CharField(blank=True, db_index=True, max_length=20)),
                ("amazon_book_url", models.URLField(blank=True, max_length=1000)),
                ("amazon_source_url", models.URLField(blank=True, max_length=1000)),
                ("amazon_source_title", models.CharField(blank=True, max_length=500)),
                ("amazon_source_snippet", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("review_count", models.IntegerField(blank=True, null=True)),
                ("rating", models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("publication_date", models.CharField(blank=True, max_length=100)),
                ("cover_image_url", models.URLField(blank=True, max_length=1000)),
                ("normalized_key", models.CharField(db_index=True, max_length=600)),
                ("book_data_confidence", models.FloatField(default=0)),
                ("source_provider", models.CharField(max_length=32)),
                ("source_raw_json", models.JSONField(blank=True, default=dict)),
                ("is_childrens_book", models.BooleanField(blank=True, null=True)),
                ("is_picture_or_illustrated_book", models.BooleanField(blank=True, null=True)),
                ("book_classification_confidence", models.FloatField(default=0)),
                ("book_classification_reason", models.TextField(blank=True)),
                ("research_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="books", to="leadfinder.researchrun")),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("public_email", models.EmailField(blank=True, max_length=254)),
                ("public_phone", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("video_status", models.CharField(choices=[("not_checked", "Not checked"), ("found_trailer", "Found trailer"), ("found_animated_video", "Found animated video"), ("found_read_aloud_only", "Found read aloud only"), ("unclear", "Unclear"), ("no_public_video_found", "No public video found")], default="not_checked", max_length=32)),
                ("video_confidence", models.FloatField(default=0)),
                ("lead_score", models.IntegerField(default=0)),
                ("lead_tier", models.CharField(choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold"), ("rejected", "Rejected")], default="cold", max_length=16)),
                ("fit_reason", models.TextField(blank=True)),
                ("sales_agent_summary", models.TextField(blank=True)),
                ("suggested_pitch_angle", models.TextField(blank=True)),
                ("suggested_first_line", models.TextField(blank=True)),
                ("what_to_say", models.TextField(blank=True)),
                ("what_not_to_say", models.TextField(blank=True)),
                ("next_best_action", models.TextField(blank=True)),
                ("extraction_confidence", models.FloatField(default=0)),
                ("manual_review_status", models.CharField(choices=[("needs_review", "Needs review"), ("approved", "Approved"), ("rejected", "Rejected"), ("do_not_contact", "Do not contact")], default="needs_review", max_length=32)),
                ("do_not_contact", models.BooleanField(default=False)),
                ("missing_data_json", models.JSONField(blank=True, default=list)),
                ("warnings_json", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("author_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads", to="leadfinder.authorprofile")),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leads", to="leadfinder.book")),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("evidence_type", models.CharField(choices=[("amazon_search_result", "Amazon search result"), ("official_author_site", "Official author site"), ("contact_page", "Contact page"), ("publisher_site", "Publisher site"), ("social_profile", "Social profile"), ("youtube_result", "YouTube result"), ("vimeo_result", "Vimeo result"), ("web_search_result", "Web search result"), ("groq_extraction", "Groq extraction"), ("manual", "Manual")], max_length=32)),
                ("field_name", models.CharField(max_length=100)),
                ("field_value", models.TextField()),
                ("source_url", models.URLField(max_length=1000)),
                ("source_title", models.CharField(blank=True, max_length=500)),
                ("source_snippet", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="leadfinder.authorprofile")),
                ("book", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="leadfinder.book")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="leadfinder.lead")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SalesAgentBrief",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("brief_markdown", models.TextField()),
                ("call_notes", models.TextField(blank=True)),
                ("outreach_angle", models.TextField(blank=True)),
                ("objection_notes", models.TextField(blank=True)),
                ("source_links_json", models.JSONField(blank=True, default=list)),
                ("lead", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="brief", to="leadfinder.lead")),
            ],
        ),
        migrations.CreateModel(
            name="SearchQueryLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("query", models.TextField()),
                ("provider", models.CharField(max_length=32)),
                ("result_count", models.IntegerField(default=0)),
                ("status", models.CharField(choices=[("success", "Success"), ("failed", "Failed")], default="success", max_length=16)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("book", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="search_logs", to="leadfinder.book")),
                ("research_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="search_logs", to="leadfinder.researchrun")),
            ],
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("snippet", models.TextField(blank=True)),
                ("rank", models.IntegerField()),
                ("provider", models.CharField(max_length=32)),
                ("classification", models.CharField(choices=[("amazon_book", "Amazon book"), ("author_site", "Author site"), ("publisher_site", "Publisher site"), ("youtube", "YouTube"), ("vimeo", "Vimeo"), ("instagram", "Instagram"), ("facebook", "Facebook"), ("tiktok", "TikTok"), ("linkedin", "LinkedIn"), ("goodreads", "Goodreads"), ("unrelated", "Unrelated"), ("unclear", "Unclear")], default="unclear", max_length=32)),
                ("classification_confidence", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("search_query_log", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="leadfinder.searchquerylog")),
            ],
        ),
        migrations.CreateModel(
            name="VideoEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("video_url", models.URLField(max_length=1000)),
                ("title", models.CharField(max_length=500)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("published_at", models.CharField(blank=True, max_length=100)),
                ("source_provider", models.CharField(choices=[("youtube_api", "YouTube API"), ("web_search", "Web search"), ("manual", "Manual")], default="web_search", max_length=32)),
                ("matches_book", models.BooleanField(blank=True, null=True)),
                ("matches_author", models.BooleanField(blank=True, null=True)),
                ("is_book_trailer", models.BooleanField(default=False)),
                ("is_animated_video", models.BooleanField(default=False)),
                ("is_read_aloud", models.BooleanField(default=False)),
                ("is_author_interview", models.BooleanField(default=False)),
                ("classification_confidence", models.FloatField(default=0)),
                ("classification_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="videos", to="leadfinder.lead")),
            ],
        ),
    ]
