# Generated by Django 6.1.dev20260514114925 on 2026-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='publicist_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='representation_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='publicist_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='representation_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='salesagentbrief',
            name='pitch_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesagentbrief',
            name='pitch_direct',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesagentbrief',
            name='pitch_publicist',
            field=models.TextField(blank=True),
        ),
    ]
