# Generated by Django 6.1.dev20260514114925 on 2026-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0002_authorprofile_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='amazon_author_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='author_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='other_books',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
