# Generated by Django 6.1.dev20260514114925 on 2026-05-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0004_google_books_provider_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrun',
            name='source_provider',
            field=models.CharField(choices=[('csv', 'CSV'), ('ddgs', 'DDGS'), ('tavily', 'Tavily'), ('brave', 'Brave'), ('google', 'Google'), ('amazon_creators', 'Amazon Creators'), ('google_books', 'Google Books'), ('manual', 'Manual')], default='ddgs', max_length=32),
        ),
    ]
