# Generated by Django 6.1.dev20260514114925 on 2026-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0006_booklife_provider_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_aplus_content',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_needs_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
