# Generated by Django 6.1.dev20260514114925 on 2026-05-22 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0007_book_has_aplus_content_lead_service_needs_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentThought',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_thoughts', to='leadfinder.researchrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
