# Generated by Django 6.1.dev20260514114925 on 2026-05-22 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0008_agentthought'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSender',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password_encrypted', models.CharField(blank=True, max_length=1000)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, max_length=255)),
                ('imap_password_encrypted', models.CharField(blank=True, max_length=1000)),
                ('daily_limit', models.IntegerField(default=50)),
                ('sent_today', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('step1_sent', 'Step 1 Sent'), ('step2_sent', 'Step 2 Sent'), ('replied', 'Replied'), ('bounced', 'Bounced'), ('paused', 'Paused'), ('completed', 'Completed')], default='queued', max_length=32)),
                ('next_action_date', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='leadfinder.lead')),
                ('assigned_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='leadfinder.emailsender')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('sent', 'Sent'), ('open', 'Email Opened'), ('click', 'Link Clicked'), ('reply', 'Reply Received'), ('bounce', 'Hard Bounce'), ('unsubscribe', 'Unsubscribed')], max_length=16)),
                ('details', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leadfinder.campaignenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft', max_length=16)),
                ('senders', models.ManyToManyField(blank=True, related_name='campaigns', to='leadfinder.emailsender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaignenrollment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='leadfinder.outreachcampaign'),
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('delay_days', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='leadfinder.outreachcampaign')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('campaign', 'step_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='campaignenrollment',
            unique_together={('campaign', 'lead')},
        ),
    ]
