# Generated by Django 6.1.dev20260522175433 on 2026-08-01 00:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0010_align_outreach_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='verification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='verification_reasons_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='verification_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not verified'), ('other', 'Other')], db_index=True, default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='verification_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContactCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=16)),
                ('role', models.CharField(choices=[('author', 'Author'), ('author_business', 'Author business'), ('agent', 'Agent or representation'), ('publicist', 'Publicist or booking'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('raw_value', models.CharField(max_length=500)),
                ('normalized_value', models.CharField(max_length=500)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not verified'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('verification_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('deliverability_status', models.CharField(blank=True, default='not_checked', max_length=32)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('selected_reason', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_candidates', to='leadfinder.lead')),
            ],
            options={
                'ordering': ['-is_primary', '-verification_score', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='contact_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='leadfinder.contactcandidate'),
        ),
        migrations.AddField(
            model_name='lead',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_leads', to='leadfinder.contactcandidate'),
        ),
        migrations.CreateModel(
            name='SocialProfileAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(db_index=True, max_length=32)),
                ('profile_url', models.URLField(max_length=1000)),
                ('normalized_handle', models.CharField(blank=True, max_length=255)),
                ('fetch_method', models.CharField(blank=True, max_length=64)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('blocked', 'Blocked'), ('unavailable', 'Unavailable'), ('error', 'Error')], default='pending', max_length=16)),
                ('profile_name', models.CharField(blank=True, max_length=500)),
                ('biography', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('external_urls_json', models.JSONField(blank=True, default=list)),
                ('extracted_contacts_json', models.JSONField(blank=True, default=list)),
                ('identity_score', models.PositiveSmallIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_audits', to='leadfinder.authorprofile')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_audits', to='leadfinder.lead')),
            ],
            options={
                'ordering': ['platform', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('not_verified_count', models.PositiveIntegerField(default=0)),
                ('other_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('research_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_batches', to='leadfinder.researchrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown')], max_length=16)),
                ('score_delta', models.SmallIntegerField(default=0)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('checker_version', models.CharField(default='v1', max_length=32)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='leadfinder.verificationbatch')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='leadfinder.contactcandidate')),
            ],
            options={
                'ordering': ['checked_at', 'check_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactcandidate',
            constraint=models.UniqueConstraint(fields=('lead', 'channel', 'normalized_value'), name='unique_contact_candidate_per_lead'),
        ),
        migrations.AddConstraint(
            model_name='contactcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('lead',), name='one_primary_contact_per_lead'),
        ),
        migrations.AddConstraint(
            model_name='socialprofileaudit',
            constraint=models.UniqueConstraint(fields=('lead', 'platform', 'profile_url'), name='unique_social_profile_per_lead'),
        ),
    ]
