# Generated by Django 5.2.16 on 2026-08-03 17:31

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0011_contact_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledLeadTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for this scheduled hunt', max_length=255)),
                ('keyword', models.CharField(help_text='Search keyword query', max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('interval_hours', 'Every X hours'), ('weekly', 'Weekly'), ('specific_days', 'Specific days of the week')], default='daily', max_length=32)),
                ('interval_hours', models.PositiveSmallIntegerField(default=24)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('run_time', models.TimeField(default=datetime.time(8, 0))),
                ('only_new_books', models.BooleanField(default=True)),
                ('target_verified_leads', models.PositiveSmallIntegerField(default=50)),
                ('require_contact', models.CharField(choices=[('email_or_phone', 'Verified email or phone'), ('email_only', 'Verified email required')], default='email_or_phone', max_length=32)),
                ('verify_email_mx', models.BooleanField(default=True)),
                ('source_provider', models.CharField(choices=[('ddgs', 'DDGS'), ('tavily', 'Tavily'), ('brave', 'Brave'), ('google', 'Google')], default='ddgs', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('execution_status', models.CharField(choices=[('idle', 'Ready'), ('running', 'Running'), ('failed', 'Needs attention')], db_index=True, default='idle', max_length=16)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_runs_count', models.PositiveIntegerField(default=0)),
                ('total_verified_leads_found', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_active', 'next_run_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='researchrun',
            name='scheduled_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='leadfinder.scheduledleadtask'),
        ),
    ]
