# Generated by Django 5.2.16 on 2026-08-03 22:50

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("leadfinder", "UserProfile")
    for user in User.objects.all().iterator():
        role = "super_admin" if user.is_superuser else "admin" if user.is_staff else "sales"
        UserProfile.objects.get_or_create(user_id=user.id, defaults={"role": role})


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0012_scheduled_lead_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignmentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('daily_lead_count', models.PositiveSmallIntegerField(default=20)),
                ('days_of_week', models.JSONField(default=list)),
                ('run_time', models.TimeField(default=datetime.time(9, 0))),
                ('contact_requirement', models.CharField(choices=[('any', 'Any lead'), ('email_or_phone', 'Email or phone required'), ('email_only', 'Email required'), ('phone_only', 'Phone required'), ('email_and_phone', 'Email and phone required'), ('verified_contact', 'Verified contact required')], default='email_or_phone', max_length=24)),
                ('verified_only', models.BooleanField(default=False)),
                ('minimum_lead_score', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_assigned', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignment_schedules', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'next_run_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentScheduleRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('requested_count', models.PositiveSmallIntegerField(default=0)),
                ('assigned_count', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='leadfinder.leadassignmentschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super admin'), ('admin', 'Admin'), ('sales', 'Salesperson')], db_index=True, default='sales', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_available_for_assignment', models.BooleanField(db_index=True, default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadfinder_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('contacted', 'Contacted'), ('follow_up', 'Follow up'), ('completed', 'Completed'), ('converted', 'Converted'), ('not_interested', 'Not interested'), ('no_response', 'No response'), ('invalid_data', 'Invalid or fake data'), ('duplicate', 'Duplicate')], db_index=True, default='pending', max_length=24)),
                ('contact_quality', models.CharField(choices=[('unchecked', 'Not checked'), ('complete', 'Email and phone complete'), ('email_only', 'Email only'), ('phone_only', 'Phone only'), ('missing_contact', 'No usable contact'), ('fake_or_invalid', 'Fake or invalid data'), ('wrong_person', 'Wrong person')], default='unchecked', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leadfinder.lead')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='leadfinder.leadassignmentschedule')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['assigned_to', 'is_current', 'status'], name='leadfinder__assigne_b05b1e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('lead',), name='one_current_assignment_per_lead')],
            },
        ),
    ]
