# Generated by Django 5.2.16 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadfinder", "0013_leadassignmentschedule_leadassignmentschedulerun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="uploader_attested",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="uploader_attested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
