# Generated by Django 6.1.dev20260522175433 on 2026-08-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinder', '0014_lead_uploader_attestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacts_flagged_stale_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacts_stale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='socialprofileaudit',
            name='follower_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchrun',
            name='source_provider',
            field=models.CharField(choices=[('csv', 'CSV'), ('ddgs', 'DDGS'), ('tavily', 'Tavily'), ('brave', 'Brave'), ('google', 'Google'), ('amazon_creators', 'Amazon Creators'), ('google_books', 'Google Books'), ('booklife', 'BookLife'), ('kickstarter', 'Kickstarter campaigns'), ('goodreads_giveaways', 'Goodreads giveaways'), ('scbwi', 'SCBWI directory'), ('amazon_new_releases', 'Amazon new releases'), ('manual', 'Manual')], default='ddgs', max_length=32),
        ),
    ]
